version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - paradedb-data:/var/lib/postgresql/data

volumes:
  paradedb-data:
